name: primeiro-workflow
run-name: Primeiro Workflow
# arrays podem ser usados com [] ou -, exemplo
# on: [push] ou 
# on:
#   - push
on: [push]

# rodar somente quando o evento for na branch main
# on:
#     push:
#       branches:
#         - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Primeiro passo
      run: echo "Deu bom!"
      
